# Enable version updates for npm dependencies
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "vite"
        update-types:
          - "version-update:semver-major"