# Enable version updates for npm dependencies
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      ignore:
        - dependency-name: "react"
          versions:
            - "16.x"
        - dependency-name: "react-dom"
          versions:
            - "16.x"  
        - dependency-name: "vite"
          versions:
            - "7.x"

